name: Deploy Logic App

on:
  workflow_dispatch:

env:
  RG_NAME: 'rg-apim-logicapp'
  LOGIC_APP_NAME: 'logi-xrosfgam7ozqy'
  LOGICAPP_PACKAGE_PATH: 'src/workflow'  

jobs:
  logic_app_build-deploy:

    name: Build 
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Package logic
        run: | 
          cd ${{ env.LOGICAPP_PACKAGE_PATH }}
          mkdir -p output
          zip -r ./output/logic.zip .

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ env.LOGICAPP_PACKAGE_PATH }}/output/

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Deploy to Azure Logic App
        uses: Azure/functions-action@v1
        id: la
        with:
          app-name: ${{ env.LOGIC_APP_NAME }}
          package: '${{ env.LOGICAPP_PACKAGE_PATH }}/output'
